### ISSUE TITLE
Create a BasketButton component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#18]
**Create a BasketButton (drawn in [MainMenu](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=MhM3uuRmItYq6QuI-0))**

- [x] Create a BasketButton component in the atoms folder
- [x] It has to receive the `count` prop
- [x] It has to match the [UIX design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=MhM3uuRmItYq6QuI-0)

**Comment by SureshPradhana** [comment]
i will take this one

**Comment by Hudayberdiev2000** [comment]
I'll take this.
