### ISSUE TITLE
Create a DeliveryOrderCard

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#19]
![image](https://github.com/user-attachments/assets/ceaed82d-28e6-4246-99da-a7ca2d8e2852)

- [ ] Create a DeliveryOrderCard in atoms folder
- [ ] I should receive `title` and `tel` props

**Comment by SureshPradhana** [comment]
i will take this one

**Comment by bruno-keiko** [comment]
> i will take this one

All of this is yours :)
