### ISSUE TITLE
Module Not Found Error on localhost:3000/

### ISSUE THREAD

**Issue by SureshPradhana** [bruno-keiko/Restaurant-app#20]
**Describe the Bug**  
A "Module not found" error occurs when navigating to the route `localhost:3000/`.

**To Reproduce**  
Steps to reproduce the error:
1. `cd Restaurant-app`
2. `npm install`
3. `npm run dev`
4. Visit `localhost:3000`
5. Observe the following error:
   ```
   https://nextjs.org/docs/messages/module-not-found
   GET / 500 in 1006ms
   ⨯ ./src/app/layout.tsx:3:1
   Module not found: Can't resolve './globals.css'
     1 | import type { Metadata } from "next";
     2 | import { Inter } from "next/font/google";
   > 3 | import "./globals.css";
       | ^
     4 |
     5 | const inter = Inter({ subsets: ["latin"] });
     6 |
   ```

**Comment by bruno-keiko** [comment]
> **Describe the Bug** A "Module not found" error occurs when navigating to the route `localhost:3000/`.
> 
> **To Reproduce** Steps to reproduce the error:
> 
> 1. `cd Restaurant-app`
> 2. `npm install`
> 3. `npm run dev`
> 4. Visit `localhost:3000`
> 5. Observe the following error:
>    ```
>    https://nextjs.org/docs/messages/module-not-found
>    GET / 500 in 1006ms
>    ⨯ ./src/app/layout.tsx:3:1
>    Module not found: Can't resolve './globals.css'
>      1 | import type { Metadata } from "next";
>      2 | import { Inter } from "next/font/google";
>    > 3 | import "./globals.css";
>        | ^
>      4 |
>      5 | const inter = Inter({ subsets: ["latin"] });
>      6 |
>    ```

Currently, we are working on building components. You can view our components by running 'npm run storybook'. By the way, I fixed this error.
