### ISSUE TITLE
Create a PopularDishCard component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#22]
- [ ] Create a PopularDishCard component in the atoms folder
- [ ] It has to receive `image` and `link` props
- [ ] It should match the [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=p65VYf1G4GSTU3FP-0)

![image](https://github.com/user-attachments/assets/f67bbae6-0e06-4efe-80af-f02c511d9241)

**Comment by Hudayberdiev2000** [comment]
i will take this
