### ISSUE TITLE
Create a HighlightCard component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#23]
- [ ] Create a HighlightCard in molecules folder
- [ ] It should receive `img` , `title`, `description`, and `link` props
- [ ] It should match to UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=p65VYf1G4GSTU3FP-0)
![Screenshot from 2024-08-12 12-45-03](https://github.com/user-attachments/assets/ef254b22-eb6f-4833-a56b-28d9a4be3e1f)

**Comment by Hudayberdiev2000** [comment]
I've already done this one.
