### ISSUE TITLE
Add Copyright symbol to CopyrightInfo component's storybook.

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#27]
**Describe the bug**
It seems that the copyright symbol is not displaying as it should.

**To Reproduce**

1. Go to (https://restaurant-app-components.vercel.app/?path=/docs/atoms-copyrightinfo--docs)

**Comment by prashantrai-30** [comment]
Hey @bruno-keiko can you assign this to me.

**Comment by bruno-keiko** [comment]
> Hey @bruno-keiko can you assign this to me.
Hello, I have assigned this task to you.
