### ISSUE TITLE
Create a ReviewCard 

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#28]
**Create a ReviewCard**
![image](https://github.com/user-attachments/assets/5db8a39b-e0a4-4d30-9659-f8631bf4dc42)

- [ ] Create a ReviewCard in molecules folder
- [ ] It has to receive `reviewer`, `comment`, `image`, and `rate`.
- [ ] It hast to match with UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=xLcL6owg7yKdD8Si-0).

**Comment by Hudayberdiev2000** [comment]
I will take this!

**Comment by devendra0009** [comment]
Hi @bruno-keiko , i can work on this if no one has picked it up yet.

**Comment by bruno-keiko** [comment]
> Hi @bruno-keiko , i can work on this if no one has picked it up yet.

I have assigned it to you!

**Comment by Hudayberdiev2000** [comment]
i have done this(

**Comment by bruno-keiko** [comment]
Hey @devendra0009 
Are you currently working on this issue? If you're facing any problems, please let us know. Thanks!

**Comment by devendra0009** [comment]
Really sorry @bruno-keiko , i got busy on some other work and forgot about this one
I'll start it today and will let you know if any problem occurs

**Comment by devendra0009** [comment]
hey @bruno-keiko , i have just started with the setup, can u just give a breif or some source on how to get started with building, in which folder should i build it because rn it is just showing a hello world message with some components folder in it. Should i make a separate component of review card ?

**Comment by bruno-keiko** [comment]
> hey @bruno-keiko , i have just started with the setup, can u just give a breif or some source on how to get started with building, in which folder should i build it because rn it is just showing a hello world message with some components folder in it. Should i make a separate component of review card ?

Hi @devendra0009 
We are currently building components. You can view them by using the `npm run storybook` command. In storybook, you can see your builder component. Refer to other components for guidance.
