### ISSUE TITLE
Create a BranchCard

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#29]
![image](https://github.com/user-attachments/assets/cd171376-35d4-447e-8c66-8b6cf3375be6)

- [ ] Create a BranchCard in molecules folder
- [ ] It should receive `name`, `address`, `time`, `tel`, `location` props
- [ ] It should match with UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=xLcL6owg7yKdD8Si-0)

**Comment by SureshPradhana** [comment]
I'd like to work on this. Assign it to me?

**Comment by bruno-keiko** [comment]
> I'd like to work on this. Assign it to me?

I have assigned it to you!
