### ISSUE TITLE
Create InfoCard

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#3]
**Create InfoCard component**

- [x] It should be created inside the atoms folder (similar to the Button component)
- [x] It should match the design. 
![Screenshot from 2024-07-31 14-06-27](https://github.com/user-attachments/assets/4211cf15-8f79-4642-81fa-d0fd32460f7a)
- [x] It should accept two props (icon and title).
- [x] The title props should be able to be a string or a React node.

**Comment by Hudayberdiev2000** [comment]
i will take this
