### ISSUE TITLE
Create a Header Component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#35]
Create a Header Component in the molecules folder
![image](https://github.com/user-attachments/assets/75771686-a516-4109-8cc5-2a8ca953026f)

Use our "atom components"
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)

**Comment by Hudayberdiev2000** [comment]
I'd like to do this one.
