### ISSUE TITLE
Create a FoodDelivery component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#36]
Create a FoodDelivery Component in the molecules folder
![image](https://github.com/user-attachments/assets/0df23e78-2363-4066-83e6-9f92b06dc2fa)
Use our "atom components"
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)

**Comment by yhlass7** [comment]
I got this job.
