### ISSUE TITLE
Create an Achievement component.

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#37]
![image](https://github.com/user-attachments/assets/f5dd9327-3d6f-4df9-8e41-e8465051c7e2)

- [ ] It should be in the atoms folder
- [ ] It should receive `title`, `description`, `image` props
- [ ] It should match to our UI/UX design
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)

**Comment by Fridish** [comment]
I would love to do this one :)

**Comment by bruno-keiko** [comment]
> I would love to do this one :)

I have assigned this issue. Thank you for your contribution!
