### ISSUE TITLE
Create a BigOfferCard component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#39]
- [ ] Create a BigOfferCard component in the atoms folder.
- [ ] It should receive `image` and `link` props
- [ ] It should match our design
![image](https://github.com/user-attachments/assets/6d5ea6bc-bd09-4a70-a9cf-9c45668bed1b)
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)

**Comment by Hudayberdiev2000** [comment]
I wanna work on this.

**Comment by devendra0009** [comment]
hey @bruno-keiko , can you assign me this

**Comment by Hudayberdiev2000** [comment]
I have completed this issue, and this have been merged. So you can remove the issue @bruno-keiko.
