### ISSUE TITLE
Create CopyrightInfo component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#4]
**Create CopyrightInfo component**

- [ ] It should be created in the atoms folder.
- [ ] It should receive `text` props
- [ ] It should match to the design
![Screenshot from 2024-07-31 14-25-34](https://github.com/user-attachments/assets/ed966cd5-774a-4f28-b04c-b36b40ba473f)

**Comment by Hudayberdiev2000** [comment]
I can take up this issue bro.
