### ISSUE TITLE
Create a Hero component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#40]
![image](https://github.com/user-attachments/assets/fba6fe1f-a3b8-4377-afcf-0ea479e0affa)

- [ ]  Create a Hero component in the atoms folder.
- [ ]  It should receive image, title and subtitle props
- [ ]  It should match our design
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)

**Comment by yhlass7** [comment]
I got this job.

**Comment by bruno-keiko** [comment]
> I got this job.

I have assigned it to you!

**Comment by yhlass7** [comment]
That's good, then.

**Comment by devendra0009** [comment]
if it's not completed , how about i pick this ? @yhlass7  @bruno-keiko

**Comment by bruno-keiko** [comment]
@devendra0009  I assigned it to you. Thank you!
