### ISSUE TITLE
Create a OurStoryCard

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#41]
- [ ] Create an OurStoryCard in the molecules folder
- [ ] It should receive `image`, `story`, `mode` props
- [ ] `story` prop should allow the display of rich text
- [ ] `mode` prop should be `primary` or `secondary` (image in left side, image in right side)

![image](https://github.com/user-attachments/assets/1e2a881a-8d0d-4303-aaac-785bc01c8494)

**Comment by SureshPradhana** [comment]
i'll work on this
