### ISSUE TITLE
Create a MemberCard

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#42]
- [ ] Create a MemberCard in the molecules folder
- [ ] It should receive `name`,` about`, `image`, and `socialMedia`  props

![image](https://github.com/user-attachments/assets/28dd0eee-b496-4a4f-ac7a-9425174a470f)

**Comment by SureshPradhana** [comment]
I'd like to work on this issue.

**Comment by bruno-keiko** [comment]
> I'd like to work on this issue.

I have assigned it to you.
