### ISSUE TITLE
Create a SpecialServiceCard component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#43]
- [ ] Create SpecialServiceCard component in the atoms folder
- [ ] It should receive name, description props
Our UI/UX Figma template is [here.](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=creqkC3RyRtLO9UH-0)
![image](https://github.com/user-attachments/assets/9ccb4f8d-5fe2-4266-b391-dcd2669ac1a7)

**Comment by Sadiquehmd** [comment]
Hi, I'd like to work on this issue.

**Comment by bruno-keiko** [comment]
> Hi, I'd like to work on this issue.

I assigned it to you! Good luck!
