### ISSUE TITLE
Create a MainCarousel component 

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#60]
1. Create a MainCarousel component in the molecules folder
2. Use Swiper.js
3. Use Reusable components
4. It should match to our [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&node-type=frame&t=6NWrBgt7ZCfa0pTK-0)

![image](https://github.com/user-attachments/assets/6cc46922-7ddc-46c1-aa95-486618c34970)

**Comment by syedaCodes** [comment]
I can do this! @bruno-keiko

**Comment by bruno-keiko** [comment]
> I can do this! @bruno-keiko

I have assigned it. Good luck!
