### ISSUE TITLE
Create RichAndHealthy Section

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#61]
1. Create a RichAndHealthy Section in Organism folder
2. Should be used reusable components
3. It should match to our UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&node-type=frame&t=6NWrBgt7ZCfa0pTK-0)

![image](https://github.com/user-attachments/assets/1f85b3aa-4ca4-446d-b9bb-c820f9637b40)

**Comment by Hudayberdiev2000** [comment]
i wanna work on this
