### ISSUE TITLE
Create BigOffer component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#62]
1. Create a BigOffer component in the organisms folder
2. Use Swiper.js
3. It should match our [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&node-type=frame&t=6NWrBgt7ZCfa0pTK-0)

![image](https://github.com/user-attachments/assets/6f5bead0-aae1-471c-92fd-4e507ab74ff2)

**Comment by ssugam10** [comment]
Kindly assign this issue to me, I believe I would be able to contribute positively

**Comment by bruno-keiko** [comment]
> Kindly assign this issue to me, I believe I would be able to contribute positively

I have assigned it. Good luck
