### ISSUE TITLE
Delivery section

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#64]
1. Create a DeliverySection component in the organisms folder
2. Use reusable component 
3. I should  match our [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&node-type=frame&t=6NWrBgt7ZCfa0pTK-0)

![image](https://github.com/user-attachments/assets/1f77fa8d-0114-4684-b8d4-1729fe84a83f)

**Comment by FloCheru** [comment]
I take this !
