### ISSUE TITLE
Create a Navbar component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#7]
- [ ] Create a Navbar component in the atoms folder.
- [ ] It should receive a navbarLinks props array that contains a label and href for each item.
- [ ] It should match the UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=UF4hHXSlrHt7PIki-0)
![image](https://github.com/user-attachments/assets/117607d8-fd17-4bbb-a8f0-a73d5f6e32c5)

**Comment by yhlass7** [comment]
suny men alyan

**Comment by yhlass7** [comment]
i will take this
