### ISSUE TITLE
Dark/light Mode Integration 

### ISSUE THREAD

**Issue by kumartushar0605** [bruno-keiko/Restaurant-app#83]

**Comment by FloCheru** [comment]
Hello can I take this ? Do you have any dark design on figma ?

**Comment by bruno-keiko** [comment]
> Hello can I take this ? Do you have any dark design on figma ?
We currently do not have a UI/UX designer. It would be better if we could find one.

**Comment by mahenoorsalat** [comment]
@bruno-keiko  I can do that dark mode integration for this repo in figma and also coded assign it to me
