### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by david-solomon-henshaw** [bruno-keiko/Restaurant-app#88]
There is a Typo in the component specialMenu.tsx specifically its Header which is: SPECIALS MANU FOR ALL TIME: when it should be SPECIAL MEUNS FOR ALL TIME , i would like to work on this if it can be assigned to me

**Comment by bruno-keiko** [comment]
@david-solomon-henshaw  Go for it

**Comment by david-solomon-henshaw** [comment]
@bruno-keiko  thanks alot can you please add the hacktoberfest label to it ?

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
Hi everyone, @david-solomon-henshaw "SPECIAL MEUNS FOR ALL TIME" or "SPECIAL MENUS FOR ALL TIME" ?

**Comment by david-solomon-henshaw** [comment]
@Rachad-Alabi-ADEKAMBI good day bro i have been assigned the issue already sorry bro. i hope u find another one i was just waiting for @bruno-keiko to add the hacktoberfest label to it.

**Comment by bruno-keiko** [comment]
Our project's purpose is only for learning, you could create other complex issues to code more
