### ISSUE TITLE
 Social Media Links Not Connected to Specific Accounts

### ISSUE THREAD

**Issue by sambhavbohra** [bruno-keiko/Restaurant-app#98]
Social Media Links Not Connected to Specific Accounts

### Problem:
The social media icons in the website's footer are not linked to any specific social media accounts. They currently point to `#`, leading to a broken or incomplete user experience.

### Proposed Solution:
1. Update the social media links to point to the appropriate social media profiles or accounts.
2. Ensure that each icon redirects users to the corresponding social media page for the website or organization.

### Steps:
- Facebook: Link to the Facebook account page.
- Twitter: Link to the Twitter profile.
- Instagram: Link to the Instagram profile.
- LinkedIn: Link to the LinkedIn profile.

##Screenshot 
![DELIVERY](https://github.com/user-attachments/assets/b2e1783b-32c3-4e3e-a392-e7a906378dd1)

**Comment by sambhavbohra** [comment]
@bruno-keiko Please assign me this issue !!

**Comment by bruno-keiko** [comment]
I'm sorry, but it is not an issue for us. Our purpose is to learn something and enhance our code quality. You could open an issue for complex things
